config/routes.rb
Rails.application.routes.draw do
  resources :plants
  resources :cathegories

    root 'welcome#index'
    

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/cathegory.rb
class Cathegory < ActiveRecord::Base
  has_many :plant, dependent: :destroy
end

app/models/plant.rb
class Plant < ActiveRecord::Base
    belongs_to :cathegory, dependent: :destroy
    mount_uploader :foto, FotoUploader
    validates :name, presence: true
    
    # It returns the articles whose titles contain one or more words that form the query
  def self.search(query)
    # where(:title, query) -> This would return an exact match of the query
    where("name like ?", "%#{query}%") 
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cathegories_controller.rb
class CathegoriesController < ApplicationController
   def index
    @cathegories = Cathegory.all
   end
  
  def show
    @cathegory = Cathegory.find(params[:id])
    
  end
    
    def new
        @cathegory = Cathegory.new
    end
    
    def edit
        @cathegory = Cathegory.find(params[:id])
    end
      
    def create
        @cathegory = Cathegory.new(cathegory_params)
        if @cathegory.save
        redirect_to @cathegory
        else
        render 'new'
        end
    end
   
    def update
    @cathegory = Cathegory.find(params[:id])
        if @cathegory.update(cathegory_params)
        redirect_to @cathegory
        else
        render 'edit'
        end
    end
    
    def destroy
        @cathegory = Cathegory.find(params[:id])
        @cathegory.destroy
        redirect_to cathegories_path
    end

 private
  def cathegory_params
    params.require(:cathegory).permit(:cat, :description)
  end
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
    def index
    @plants = Plant.all
    
        if params[:search]
          @plants = Plant.search(params[:search])
        end
    end
    

  def show
    @plant = Plant.find(params[:id])
    
  end
    
    def new
        @plant = Plant.new
        #plant.foto = params[:file]
        
    end
    
    def edit
        @plant = Plant.find(params[:id])
    end
      
    def create
        @plant = Plant.new(plant_params)
        if @plant.save
        redirect_to @plant
        
        end
    end
   
    def update
        @plant = Plant.find(params[:id])
        if @plant.update(plant_params)
        redirect_to @plant
        else
        render 'edit'
        end
    end
    def destroy
     @plant = Plant.find(params[:id])
     @plant.destroy
     redirect_to plants_path
    end


 private
  def plant_params
    params.require(:plant).permit(:name, :latin, :family, :condition, :foto)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cathegories_helper.rb
module CathegoriesHelper
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/cathegories/edit.html.erb
<h1>Editing cathegory</h1>
 <%= form_for :cathegory, url: cathegory_path(@cathegory), method: :patch do |f| %>
   
   <p>
    <%= f.label :cat %><br>
    <%= f.text_field :cat %>
  </p>
   <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
   <p>
    <%= f.submit %>
  </p>
   <% end %>
 <%= link_to 'Back', cathegories_path %>

app/views/cathegories/index.html.erb
<h1>Kategorie</h1>

 <%= link_to 'Nowa kategoria', new_cathegory_path %>
<table>
  <tr>
    <th>Cathegory</th>
    <th colspan="2"></th>
  </tr>
   <% @cathegories.each do |cathegory| %>
    <tr>
      <td><%= cathegory.cat %></td>
      <td><%= link_to 'Pokaż', cathegory_path(cathegory) %></td>
      <td colspan="2"></td><td><%= link_to 'Edytuj', edit_cathegory_path(cathegory) %></td>
      <td colspan="2"></td> <td><%= link_to 'Usuń', cathegory_path(cathegory)%></td>
    </tr>
  <% end %>
  <% if @cathegories.size == 0 %>
    <em> Brak wpisów </em>
    <% end %>
</table>

app/views/cathegories/new.html.erb
<h1>New Cathegory</h1>
<%= form_for :cathegory, url: cathegories_path do |f| %>
   
  <p>
    <%= f.label :cat %><br>
    <%= f.text_field :cat %>
  </p>
   <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
   <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', cathegories_path %>

app/views/cathegories/show.html.erb
<p>
  <strong>Cathegory:</strong>
  <%= @cathegory.cat %>
</p>
 <p>
  <strong>Description:</strong>
  <%= @cathegory.description %>
</p>


<%= link_to 'Back', cathegories_path %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Encyklopedia Roślin
    by Hanna Buczyńska</a>
  </small>
  
</footer>

app/views/layouts/_header.html.erb
 <header class="navbar navbar-default navbar-static-top">   
      <nav>
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
           
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Home",   root_path %></li>
            <li><a href="#">Informacje</a></li>
            <li><a href="#">Galeria</a></li>
         
         
        <li><%= link_to "Rośliny",   plants_path %></li>
        <li><%= link_to "Kategorie",   cathegories_path %></li>
        <li><%= link_to "Help",   '#' %></li>
        <li><%= link_to "Log in", '#' %></li>
        <li>
        </ul>
            
          <ul class="nav navbar-nav navbar-right">  
          <form class="navbar-form navbar-left" role="search">
          <div class="form-group">
           
            <%= form_tag(plants_path, :method => "get", class: "navbar-form", id: "search-form") do %>
            <%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Szukaj" %>
        </div>
        <button type="submit" class="btn btn-default">Szukaj</button>
      </form>
      <% end %>
        </li>
      </ul>
    </nav>
<%= link_to image_tag("meczennica_f3.jpg", id: "banner"), '#' %>
  <div class="container">
    
    <%= link_to "Encyklopedia Roślin", '#', id: "logo" %>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Encyklopedia Roślin</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
 <body>
        <%= render 'layouts/header' %>
        

      <div class="container">
        
    
<%= yield %>
<p></p>
      <%= render 'layouts/footer' %>

</body>
</html>

app/views/plants/edit.html.erb
<h1>Editing cathegory</h1>
 <%= form_for :plant, url: plant_path(@plant), method: :patch do |f| %>
   
   <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :latin %><br>
    <%= f.text_field :latin %>
  </p>
  <p>
    <%= f.label :family %><br>
    <%= f.text_area :family %>
  </p>
   <p>
    <%= f.label :condition %><br>
    <%= f.text_area :condition %>
  </p>
  <p>
      <%= f.label :foto %><br>
      <%= f.file_field :foto %>
  </p>
   <p>
    <%= f.submit %>
  </p>
   <% end %>
 <%= link_to 'Back', plants_path %>

app/views/plants/index.html.erb
<h1>Rośliny</h1>

<%= link_to 'Nowa', new_plant_path %>
<table>
  <tr>
    <th>Nazwa</th>
    <th colspan="2"></th>
  </tr>
   <% @plants.each do |plant| %>
    <tr>
      <td><%= plant.name %></td>
      <td><%= link_to 'Show', plant_path(plant) %></td>
      <td><%= link_to 'Edit', edit_plant_path(plant) %></td>
      <td><%= link_to 'Destroy', plant_path(plant),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
  
    </tr>
  <% end %>
    <% if @plants.size == 0 %>
    <em> Brak wpisów </em>
    <% end %>
</table>

app/views/plants/new.html.erb
<h2>Nowa roślina</h2>
 
 <%= form_for :plant, url: plants_path do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :latin %><br>
    <%= f.text_field :latin %>
  </p>
  <p>
    <%= f.label :family %><br>
    <%= f.text_area :family %>
  </p>
   <p>
    <%= f.label :condition %><br>
    <%= f.text_area :condition %>
  </p>
  <p>
      <%= f.label :foto %><br>
      <%= f.file_field :foto %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>
<%= link_to 'Back', plants_path %>

app/views/plants/show.html.erb
<div class="center jumbotron">
<h1><%= @plant.name %></h1>
<h3><%= @plant.latin %></h3>
  
 <p>
  <strong>Rodzina:</strong>
  <%= @plant.family %>
</p>

<p>
    <%= image_tag @plant.foto, class: "zdjecie" %>
</p>

<p>
  <strong>Uprawa:</strong>
  <%= @plant.condition %>
</p>


<%= link_to 'Back', plants_path %>
</div>

app/views/welcome/index.html.erb
<div class="center jumbotron">

    <h1>Encyklopedia Roślin</h1>
    <p>Encyklopedia roślin to strona o uprawie roślin egzotycznych. Wpisy będą systematycznie uzupełniane.</p>
        <p>Uwagi i wskazówki mile widziane.</p>
</div>